apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: gokul72/boardgame:v1.3
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dockerhub1-secret 
